/**
 * pac.ts — Generates and installs a PAC (Proxy Auto-Config) script.
 *
 * Proxy Selection Logic (Go client parity):
 *   - Fetches latest latency data for each host from storage.
 *   - Active candidates: Hosts that have non-null (successful) latest latency checks.
 *   - If ALL hosts in a group timed out / failed, fall back to selecting randomly from ALL group hosts.
 *   - LATENCY policy: Select host with minimum latency.
 *   - RANDOM_ON_SIMILAR_LOWEST_LATENCY policy (exact Go client formula):
 *       Find lowest latency L. Candidate set includes hosts with latency < 200ms OR < L * 1.5 (3/2).
 *       Randomly select one host from this candidate set.
 *   - RANDOM policy: Randomly select from active hosts (or all hosts if all failed).
 */

import { getLatencies } from '../storage';
import type { AppSettings, HostLatency } from '../types';

export async function setProxy(settings: AppSettings): Promise<void> {
  const mode = settings.mode || (settings.enabled ? 'by_rule' : 'off');
  if (mode === 'off' || settings.proxies.every(p => p.hosts.length === 0)) {
    await clearProxy();
    return;
  }

  const latencies = await getLatencies();
  const pacScript = generatePacScript(settings, latencies);

  const config: chrome.proxy.ProxyConfig = {
    mode: 'pac_script',
    pacScript: { data: pacScript },
  };

  return new Promise<void>((resolve) => {
    chrome.proxy.settings.set({ value: config, scope: 'regular' }, () => {
      chrome.action.setIcon({ path: 'icon_on.png' }).catch(() => {});
      resolve();
    });
  });
}

export async function clearProxy(): Promise<void> {
  return new Promise<void>((resolve) => {
    chrome.proxy.settings.clear({ scope: 'regular' }, () => {
      chrome.action.setIcon({ path: 'icon_off.png' }).catch(() => {});
      resolve();
    });
  });
}

/** Build the PAC script text from the current settings and latest latency data. */
function generatePacScript(settings: AppSettings, latencies: Record<string, HostLatency>): string {
  const authPath = settings.authBasePath || '/auth/';

  // Compute latest latency map for every host (host -> latest latency ms | null)
  const hostLatencyMap: Record<string, number | null> = {};
  for (const host of Object.keys(latencies)) {
    const history = latencies[host]?.history;
    if (history && history.length > 0) {
      hostLatencyMap[host] = history[history.length - 1].latency;
    } else {
      hostLatencyMap[host] = null;
    }
  }

  // Build per-proxy group data with latest latencies embedded
  const proxyGroups = settings.proxies.map(p => ({
    name: p.name,
    hosts: p.hosts,
    policy: p.selectPolicy,
  }));

  // Rules: [{proxyName, domains[]}]
  const rules = settings.rules.map(r => ({
    proxyName: r.proxyName,
    domains: r.domains,
  }));

  // Unmatched policy
  const unmatched = settings.unmatchedPolicy;

  // Flat set of all proxy hosts to avoid routing loops
  const allHosts: string[] = [];
  for (const p of settings.proxies) allHosts.push(...p.hosts);

  const mode = settings.mode || (settings.enabled ? 'by_rule' : 'off');
  const globalPolicy = settings.globalProxyPolicy || 'LATENCY';
  const globalTarget = settings.globalProxyTarget || '';

  return `
    // Generated by Go SHP Chrome Extension
    var mode = ${JSON.stringify(mode)};
    var globalPolicy = ${JSON.stringify(globalPolicy)};
    var globalTarget = ${JSON.stringify(globalTarget)};
    var authPath = ${JSON.stringify(authPath)};
    var allProxyHosts = new Set(${JSON.stringify(allHosts)});
    var hostLatencyMap = ${JSON.stringify(hostLatencyMap)};

    // Proxy groups: [{name, hosts[], policy}]
    var proxyGroups = ${JSON.stringify(proxyGroups)};

    // Routing rules in priority order: [{proxyName, domains[]}]
    var rules = ${JSON.stringify(rules.map(r => ({
      proxyName: r.proxyName,
      domainSet: r.domains,
    })))};

    // Fallback when no rule matches
    var unmatchedProxyName = ${JSON.stringify(unmatched.proxyName)};

    // Resolve a list of hosts according to a selection policy
    function resolveHostsByPolicy(hosts, policy, specificTarget) {
      if (!hosts || hosts.length === 0) return 'DIRECT';
      if (policy === 'SPECIFIC') {
        if (specificTarget && hosts.indexOf(specificTarget) >= 0) {
          return 'HTTPS ' + specificTarget;
        }
        if (specificTarget) {
          return 'HTTPS ' + specificTarget;
        }
      }

      var activeHosts = [];
      for (var hi = 0; hi < hosts.length; hi++) {
        var h = hosts[hi];
        if (hostLatencyMap[h] !== null && hostLatencyMap[h] !== undefined) {
          activeHosts.push(h);
        }
      }

      var candidates = activeHosts.length > 0 ? activeHosts : hosts;
      if (candidates.length === 1) {
        return 'HTTPS ' + candidates[0];
      }

      if (policy === 'RANDOM') {
        var idx = Math.floor(Math.random() * candidates.length);
        return 'HTTPS ' + candidates[idx];
      }

      candidates.sort(function(a, b) {
        var latA = hostLatencyMap[a] !== null && hostLatencyMap[a] !== undefined ? hostLatencyMap[a] : 999999;
        var latB = hostLatencyMap[b] !== null && hostLatencyMap[b] !== undefined ? hostLatencyMap[b] : 999999;
        return latA - latB;
      });

      if (policy === 'LATENCY') {
        return 'HTTPS ' + candidates[0];
      }

      if (policy === 'RANDOM_ON_SIMILAR_LOWEST_LATENCY') {
        var lowest = hostLatencyMap[candidates[0]] !== null && hostLatencyMap[candidates[0]] !== undefined
          ? hostLatencyMap[candidates[0]]
          : 999999;

        var similarCount = 1;
        for (var cIdx = 1; cIdx < candidates.length; cIdx++) {
          var lat = hostLatencyMap[candidates[cIdx]] !== null && hostLatencyMap[candidates[cIdx]] !== undefined
            ? hostLatencyMap[candidates[cIdx]]
            : 999999;

          if (lat < 200 || lat < (lowest * 3 / 2)) {
            similarCount++;
          } else {
            break;
          }
        }

        var selIdx = Math.floor(Math.random() * similarCount);
        return 'HTTPS ' + candidates[selIdx];
      }

      return 'HTTPS ' + candidates[0];
    }

    // Resolve a proxy group name to a PAC proxy string (e.g. "HTTPS host:443")
    function resolveProxy(proxyName) {
      if (proxyName === 'DIRECT') return 'DIRECT';

      for (var gi = 0; gi < proxyGroups.length; gi++) {
        var g = proxyGroups[gi];
        if (g.name !== proxyName) continue;
        return resolveHostsByPolicy(g.hosts, g.policy, '');
      }

      return 'DIRECT';
    }

    // True if 'host' is a suffix of or equal to 'domain'
    function isDomainMatch(host, domainSet) {
      var parts = host.split('.');
      for (var i = 0; i <= parts.length - 1; i++) {
        var candidate = parts.slice(i).join('.');
        for (var j = 0; j < domainSet.length; j++) {
          if (domainSet[j] === candidate) return true;
        }
      }
      return false;
    }

    function FindProxyForURL(url, host) {
      // Auth-handshake URLs must go directly to the target proxy host
      if (url.indexOf(authPath + '407') >= 0) {
        var hostBegin = url.indexOf('//') + 2;
        var hostEnd   = url.indexOf('/', hostBegin);
        var proxyHost = url.slice(hostBegin, hostEnd < 0 ? undefined : hostEnd);
        return 'HTTPS ' + proxyHost;
      }

      // Avoid routing requests to the proxy servers themselves through the proxy
      if (allProxyHosts.has(host)) return 'DIRECT';

      // Mode "global": all traffic through proxy, ignore all rules
      if (mode === 'global') {
        var hostsArray = Array.from(allProxyHosts);
        return resolveHostsByPolicy(hostsArray, globalPolicy, globalTarget);
      }

      // Evaluate rules in order (mode "by_rule")
      for (var ri = 0; ri < rules.length; ri++) {
        if (isDomainMatch(host, rules[ri].domainSet)) {
          return resolveProxy(rules[ri].proxyName);
        }
      }

      // Fallback
      return resolveProxy(unmatchedProxyName);
    }
  `;
}
